# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dan Crankshaw
# tagline:          The Jekyll Butler
url:              http://dancrankshaw.com
paginate:         1
baseurl:          /
author:
  name:           Dan Crankshaw
  url:            https://twitter.com/dan_crankshaw
  email:          crankshaw@cs.berkeley.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dcrankshaw/dcrankshaw.github.io
